### ISSUE TITLE
can not mount config.json in container

### ISSUE THREAD

**Issue by kforner** [scality/cloudserver#1520]
In order to be able to use the s3 server from another linked docker container, I read that I must modify the config.json. 

The problem is that it then crashes with this error:
```
s3_1         | Log level has been modified to debug
s3_1         | mv: cannot move 'config.json.tmp' to 'config.json': Device or resource busy
analytics-engine_s3_1 exited with code 1
```
Here is the relevant part of the `docker-compose.yml` file:
```
  s3:
    image: scality/s3server
    ports:
      - "8000:8000"
    volumes:
      - "./etc/s3server/config.json:/usr/src/app/config.json"
    environment:
      LOG_LEVEL: "debug"
      #REMOTE_MANAGEMENT_DISABLE: "1"
```

I took the config.json file from the container itself and did not modifty it.
