### ISSUE TITLE
Unable to use an http location

### ISSUE THREAD

**Issue by randomswdev** [scality/cloudserver#2246]
### Description

When configuring a locationConstraint with https false, cloudserve still attmepts an https connection and reports an SSL error.

### Steps to reproduce the issue

Define a locationConstraint like:

```
locationConstraints:
    locationMinio01:
      type: aws_s3
      legacyAwsBehavior: true
      details:
        bucketMatch: true
        https: false
        awsEndpoint: minio-server.com:9001
        bucketName: minio01
        pathStyle: true
        credentials:
          accessKey: accesskey
          secretKey: secretkey
```

### Actual result

cloudserver fails to connect because of an https error:
```
{"name":"S3","error":{"code":500,"description":"We encountered an internal error. Please try again.","InternalError":true},"healthStatus":[null,{"us-east-1":{"code":200,"message":"OK"},"locationMinio01":{"error":{"message":"write EPROTO 139945897604928:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n","errno":"EPROTO","code":"NetworkingError","syscall":"write","region":"us-east-1","hostname":"minio01.minio-server.com","retryable":true,"time":"2019-11-19T19:17:48.480Z"},"external":true},"mongoclient":{"code":200,"description":"No error","ok":true},"vaultMem":{"code":200,"message":"OK"}}],"time":1574191068501,"req_id":"6c27a63ecb46a76676b3","level":"info","message":"initial health check failed, delaying startup","hostname":"zenko-cloudserver-6969b765d-2gjr8","pid":19}
```

### Expected result

A successfull, plain http, connection to the minio server.
