### ISSUE TITLE
Failed to start cloudserver container when setting ENDPOINT environment variable

### ISSUE THREAD

**Issue by ronniel1** [scality/cloudserver#2550]
### Description
Using zenko/cloudserver container to deploy S3 server on OpenShift.
When I set the ENDPOINT environment variable of the container, the container fails to start with the following error:
`Host name has been modified to afc5623509a00441e824e3ba8d328162-1572154092.eu-central-1.elb.amazonaws.com
Note: In your /etc/hosts file on Linux, OS X, or Unix with root permissions, make sure to associate 127.0.0.1 with afc5623509a00441e824e3ba8d328162-1572154092.eu-central-1.elb.amazonaws.com
/usr/src/app/docker-entrypoint.sh: line 199: config.json.tmp: Permission denied`

### Steps to reproduce the issue

My deployment file:
```
  metadata:
      labels:
        app: scality
    spec:
      containers:
        - image: zenko/cloudserver
          imagePullPolicy: Always
          name: s3server
          envFrom:
            - configMapRef:
                name: s3-config
          volumeMounts:
            - mountPath: /mnt/data
              name: scalityvol
      volumes:
        - name: scalityvol
          persistentVolumeClaim:
            claimName: scality-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scality
  name: scality
  namespace: assisted-installer
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: scality
  type: LoadBalancer
status:
  loadBalancer: {}
```

My configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-config
  namespace: assisted-installer
  labels:
    app: scality
data:
  S3_ENDPOINT_URL: http://afc5623509a00441e824e3ba8d328162-1572154092.eu-central-1.elb.amazonaws.com:8000
  ENDPOINT: afc5623509a00441e824e3ba8d328162-1572154092.eu-central-1.elb.amazonaws.com
  S3DATAPATH: /mnt/data
  S3METADATAPATH: /mnt/data
  AWS_ACCESS_KEY_ID: accessKey1
  AWS_SECRET_ACCESS_KEY: verySecretKey1
  SCALITY_ACCESS_KEY_ID: accessKey1
  SCALITY_SECRET_ACCESS_KEY: verySecretKey1
  REMOTE_MANAGEMENT_DISABLE: "1"
```
