### ISSUE TITLE
Docker compose environment fails with "This service may not be available in the `eu-west-1' region.`" for me

### ISSUE THREAD

**Issue by zubozrout** [scality/cloudserver#4688]
Hi,
this might be an actual issue or more likely just me not understanding how to make this work, but when I try to run my Express.js app locally using docker-compose environment, I am able to connect to localstack (AWS S3 emulation) that is running through Docker. Same goes for another s3 alternative I've tried, even though I've spent a lot of time on making that one work properly. But with zenko/cloudserver I am now most definitely lost.

Having a config like this:
```
  cloudserver:
    image: zenko/cloudserver:latest
    ports:
      - "8000:8000"
      - "9990:9990"
      - "9991:9991"
    volumes:
      - s3data:/data
      - s3metadata:/metadata
    restart: unless-stopped
    environment:
      - SCALITY_ACCESS_KEY_ID=test
      - SCALITY_SECRET_ACCESS_KEY=test
      - S3DATAPATH=/data
      - S3METADATAPATH=/metadata

volumes:
  s3data:
  s3metadata:
```

and my Express.js app that is also running as part of this docker-compose.yml file which `depends_on: cloudserver` I am getting the following error in the console:

A) ```UnknownEndpoint: Inaccessible host: `cloudserver' at port `8000'. This service may not be available in the `eu-west-1' region.```
B)
```
{"name":"S3","time":1658751603984,"error":{"code":"MODULE_NOT_FOUND","requireStack":["/usr/src/app/lib/kms/wrapper.js","/usr/src/app/lib/data/wrapper.js","/usr/src/app/lib/utilities/healthcheckHandler.js","/usr/src/app/lib/utilities/internalHandlers.js","/usr/src/app/lib/server.js","/usr/src/app/index.js"]},"level":"warn","message":"scality kms unavailable. Using file kms backend unless mem specified.","hostname":"ad1ac86529aa","pid":69}
{"name":"MetadataFileServer","time":1658751604032,"error":"Cannot find module 'ioctl' .... "level":"warn","message":"WARNING: Synchronization directory updates are not supported on this platform. Newly written data could be lost if your system crashes before the operating system is able to write directory updates.","hostname":"ad1ac86529aa","pid":111}
```

For the B part, these are all warnings so I guess they may not be preventing this to work. But I am not sure why A is failing.
Accessing http://localhost:8000 in a web browser gives me at a sign the server itself is running though.

Is there anything else needed in order for this to run? I am trying to have a server to connect to and use as a local S3 environment (saving files locally). But unfortunately I seem to be missing something. I've bumped into various resources on this, but most of them just seem out of date, like this one: https://blog.programster.org/deploy-your-own-s3-server

Thank you very much.

**Comment by sytolk** [comment]
```yaml
version: '3.9'
services:
  s3server:
    hostname: s3server
    container_name: s3server
    image: zenko/cloudserver:latest-0.0.0
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - s3data:/usr/src/app/localData
      - s3metadata:/usr/src/app/localMetadata
      - ./cloudserver/authdata.json:/usr/src/app/conf/authdata.json
    environment:
      S3BACKEND: file
#      REMOTE_MANAGEMENT_DISABLE: 1
      LOG_LEVEL: debug
      SSL: 'false'
#      LISTEN_ADDR: 0.0.0.0
  s3manager:
    container_name: s3manger
    hostname: s3manager
    image: mastertinner/s3manager
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - ENDPOINT=s3server:8000
      - ACCESS_KEY_ID=accessKey1
      - SECRET_ACCESS_KEY=verySecretKey1
      - USE_SSL=false
    depends_on:
      - s3server
volumes:
  s3data:
  s3metadata:
networks:
  default:
    name: ts-platform
```
